### ISSUE TITLE
PROGRAM 1

### ISSUE THREAD

**Issue by JAYANTH0903** [hari-eur/Maanesh---Jayanth#1]
Solve the below problem:

Write a C program that reads in a string as input from us and to print the longest palindrome that can be formed from the characters in the string.

Note:

A palindrome is a word, phrase, number, or other sequence of characters that reads the same forward and backward (ignoring spaces, punctuation, and capitalization).
If there are multiple palindromes of the same length, your program should print out the one that comes first alphabetically.
For example, if you enter the string "I have reached final level in racecar game".
your program should output "racecar".

**Comment by maanesh09** [comment]
### CODE
#include <stdio.h>

int main()
{
    char str[100];
    scanf("%s",str);
    
    int len,start,end;
    for(len=0;str[len]!='\0';len++);
    end=len-1;
    
    while(start<end){
    
        if(str[start]!=str[end]){
            
            printf("the string %s is not a pallindrome",str);
            return 0;
            
        }
        start++;
        end--;
        
    }
    printf("the string %s is a pallindrome",str);

    return 0;
}



### OUTPUT
<img width="931" alt="image" src="https://user-images.githubusercontent.com/75109376/221410207-f10e59df-7b92-4866-8b8b-9cf0d347e4a3.png">
