### ISSUE TITLE
PROGRAM 2

### ISSUE THREAD

**Issue by JAYANTH0903** [hari-eur/Maanesh---Jayanth#2]
Solve the following hacker rank problem

https://www.hackerrank.com/challenges/staircase/problem

**Comment by maanesh09** [comment]
### CODE
#include <stdio.h>

int main()
{
    int n,i,j,k;
    scanf("%d",&n);
    for(i=0;i<n;i++){
            
            for(j=0;j<n-1-i;j++){
                
                printf(" ");
                
            }
            for(k=j;k<n;k++){
                
                printf("#");
                
            }
            printf("\n");
            
            
    }

    return 0;
}


### OUTPUT
<img width="960" alt="image" src="https://user-images.githubusercontent.com/75109376/221408607-0c5a201c-1829-4131-8ba9-7753aa6b8883.png">
